---
title: "About"
---

# Bio

Ilina Odouard is a Ph.D. student concentrating in health services research and policy in the Department of Health Policy and Management at the Johns Hopkins Bloomberg School of Public Health. Her research investigates pharmaceutical regulatory and payment strategies to promote affordability and equitable access while managing spending and maintaining adequate evidence quality. Currently, her research focuses on Medicare and Medicaid payment strategies for cell and gene therapies and investment in pharmaceutical innovation. Her work has been published in JAMA, JAMA Neurology, the Journal of Managed Care and Specialty Pharmacy, Value in Health, Health Affairs Scholar, and O&G Open. Prior to becoming an academic researcher, she was a life sciences and healthcare strategy consultant in both the United States and Australia.

# Education

### Johns Hopkins Bloomberg School of Public Health | Baltimore, USA
Ph.D. in Health Services Research | August 2024 - Present
M.P.H. | June 2022 - May 2023

### Barnard College of Columbia University | New York, USA
B.A. in Neuroscience & Behavior | September 2014 - May 2018
